import { readFile, writeFile } from 'node:fs/promises';
const source = await readFile(new URL('./plugin.mjs', import.meta.url), 'utf8');
await writeFile(new URL('./plugin.js', import.meta.url), '// Generated by build.mjs; edit plugin.mjs.\n' + source);
