// Generated by build.mjs; edit plugin.mjs.
/** QuickJS ES module. No network, credential access, or process-local persistence. */
export const P = Object.freeze({
  isA: 'https://atomicdata.dev/properties/isA',
  parent: 'https://atomicdata.dev/properties/parent',
  name: 'https://atomicdata.dev/properties/name',
  description: 'https://atomicdata.dev/properties/description',
  about: 'https://atomicdata.dev/properties/about',
  localId: 'https://atomicdata.dev/properties/localId',
});
const DOCUMENTS = ['https://atomicdata.dev/classes/Document', 'https://atomicdata.dev/classes/DocumentV2'];
const MESSAGE = 'https://atomicdata.dev/classes/Message';
const MAX_BODY = 16384;
function text(value, field, max = 1024) {
  if (typeof value !== 'string' || !value.length || value.length > max || /[\u0000-\u001f\u007f]/.test(value))
    throw new Error(`Invalid ${field}`);
  return value;
}
// Deliberately restrictive HTTPS DNS origins. URL is not a QuickJS global.
export function origin(value) {
  text(value, 'origin', 255);
  if (!/^https:\/\/[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?(?::[1-9][0-9]{0,4})?$/.test(value))
    throw new Error('Expected an HTTPS origin without credentials, path or query');
  return value;
}
function subject(value, field) {
  text(value, field, 2048);
  if (!/^(https?:\/\/|did:ad:)/.test(value)) throw new Error(`Invalid ${field} subject`);
  return value;
}
function response(status, body, head = false) {
  return { status, headers: { 'content-type': 'application/json', 'cache-control': 'no-store' }, body: head ? '' : JSON.stringify(body) };
}
/** Public discovery is deliberately disabled until authenticated route writes exist. */
export function handle(ctx, request) {
  const method = request.method;
  const discovery = request.path === '/ocm-provider' || request.wellKnown === 'ocm';
  if (discovery) {
    if (method !== 'GET' && method !== 'HEAD') return response(405, { message: 'Method not allowed' });
    try {
      const base = origin(ctx.config?.publicOrigin);
      return response(200, { enabled: false, apiVersion: '1.3.0', endPoint: `${base}/ocm`, resourceTypes: [] }, method === 'HEAD');
    } catch { return response(503, { message: 'Configure publicOrigin before serving discovery' }, method === 'HEAD'); }
  }
  if (request.path === '/ocm/shares') {
    if (method !== 'POST') return response(405, { message: 'Method not allowed' });
    // Never claim a share was accepted, never trust body-provided identities.
    return response(501, { message: 'Authenticated OCM receipt requires host route authentication, writes and delivery support' });
  }
  return response(404, { message: 'Not found' });
}
/** Validate the supported 1.3 file-share subset, returning no access credentials. */
export function parseShare(body) {
  if (typeof body !== 'string' || body.length > MAX_BODY) throw new Error('Share must be a JSON string of at most 16384 characters');
  let value;
  try { value = JSON.parse(body); } catch { throw new Error('Invalid share JSON'); }
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('Invalid share object');
  if (value.shareType !== 'user' || value.resourceType !== 'file') throw new Error('Only user file shares are supported');
  if (!value.protocol || !['webdav', 'multi'].includes(value.protocol.name)) throw new Error('Only WebDAV share metadata is supported');
  const dav = value.protocol.webdav ?? value.protocol.options;
  if (!dav || typeof dav !== 'object') throw new Error('Missing WebDAV options');
  text(dav.uri, 'WebDAV uri', 2048);
  if (dav.uri.includes('://') && !/^https:\/\/[^/@?#\\]+\//.test(dav.uri)) throw new Error('Absolute WebDAV URI must use HTTPS without credentials');
  if (dav.requirements !== undefined && (!Array.isArray(dav.requirements) || dav.requirements.length)) throw new Error('WebDAV requirements are not supported');
  if (!Array.isArray(dav.permissions) || !dav.permissions.length || dav.permissions.some(p => !['read', 'write', 'share'].includes(p))) throw new Error('Unsupported WebDAV permissions');
  if (value.expiration !== undefined && (!Number.isSafeInteger(value.expiration) || value.expiration < 0)) throw new Error('Invalid expiration');
  return {
    protocol: 'webdav', permissions: [...new Set(dav.permissions)].sort(),
    ...(value.expiration === undefined ? {} : { expiration: String(value.expiration) }),
    name: text(value.name, 'name', 255),
    providerId: text(value.providerId, 'providerId'),
    owner: text(value.owner, 'owner'),
    sender: text(value.sender, 'sender'),
    shareWith: text(value.shareWith, 'shareWith'),
    shareType: 'user', resourceType: 'file',
  };
}
/** A manually reviewed metadata import, not an authenticated network receiver.
 * Config is installation-owned. Share text is supplied by the operator, never
 * copied automatically from an incoming HTTP request. The host plans/applies
 * these ordinary intents under existing scoped job permissions and review.
 */
export function run(ctx) {
  try {
    const c = ctx.config ?? {};
    if (c.mode !== 'import-reviewed-share') throw new Error('Set mode to import-reviewed-share for an operator-reviewed metadata import');
    const peer = origin(c.peerOrigin);
    if (!Array.isArray(c.allowedPeers) || !c.allowedPeers.includes(peer)) throw new Error('Peer is not allowed');
    const share = parseShare(c.shareJson);
    if (share.shareWith !== text(c.recipient, 'recipient')) throw new Error('Share recipient does not match configured recipient');
    const document = subject(c.document, 'document');
    const target = ctx.read(document);
    if (!target || !Array.isArray(target[P.isA]) || !target[P.isA].some(t => DOCUMENTS.includes(t)))
      throw new Error('Target must be an accessible Atomic Document or DocumentV2');
    // Message belongs beneath the chosen document; it cannot silently change
    // document content or ACLs, and the host checks write access to this parent.
    const identity = JSON.stringify(['ocm-receipt-v1', peer, share.providerId, share.shareWith]);
    const matches = ctx.query(P.localId, identity);
    if (!Array.isArray(matches) || matches.length > 1) throw new Error('Ambiguous existing share receipt');
    const escape = value => String(value).replace(/[\\`*_{}\[\]()<>#+.!|~-]/g, '\\$&');
    const summary = 'Operator-reviewed OCM share metadata. File content has not been imported.\n\n' +
      Object.entries({ Peer: peer, Name: share.name, 'Provider ID': share.providerId, Owner: share.owner, Sender: share.sender, Recipient: share.shareWith, Permissions: share.permissions.join(', '), Expiration: share.expiration ?? 'none' })
        .map(([key, value]) => `- ${key}: ${escape(value)}`).join('\n');
    if (matches.length) {
      const existing = ctx.read(matches[0]);
      if (!existing || existing[P.parent] !== document || existing[P.about] !== document ||
          existing[P.localId] !== identity || !existing[P.isA]?.includes(MESSAGE) || existing[P.description] !== summary)
        throw new Error('Share identity conflicts with an existing receipt; review required');
      return { intents: [], problems: [] };
    }
    return { intents: [{ op: 'create', localId: 'ocm-share-receipt', parent: document, isA: [MESSAGE], set: {
      [P.name]: `OCM share: ${share.name}`,
      [P.description]: summary,
      [P.about]: document,
      [P.localId]: identity,
    } }], problems: [] };
  } catch (error) {
    return { intents: [], problems: [{ severity: 'error', message: error.message }] };
  }
}
