// @wc-ignore-file
import {
  fetchAccountContext,
  fetchNamed,
  type RawNamed,
} from './clockifyApi.js';
import {
  absenceCandidates,
  MARGIN_MS,
  rawFromCanonical,
  readOne,
  readRange,
  timeEntries,
  totalMs,
  unknownIntervals,
  type ReadContext,
} from './clockifyObserve.js';
import type { Settings } from './config.js';
import { ObservationLog } from './observationLog.js';
import type { Mirror } from './observations.js';
import { atomic, NAME, type RowKey } from './ontology.js';
import { projectEntries, type ProjectedEntry } from './project.js';
import type { CompleteSchema } from './schema.js';
import type { JSONValue, PluginStore } from './store.js';
import type { ProxyTransport } from './transport.js';

const DAY = 86_400_000;

export interface SyncResult {
  created: number;
  updated: number;
  unchanged: number;
  /** Rows of entries Clockify confirmed deleted (GET by id: 404). */
  removed: number;
  /** Non-fatal: e.g. project names unavailable, so rows keep raw ids only. */
  warnings: string[];
  log: LogReport;
  /** The profile time zone used for the window, and the workspace's
   * forceProjects, as read this pass (absent when unknown). */
  account: { timeZone?: string; forceProjects?: boolean; weekStart?: string };
  /** The mirror after this pass, and the names read for it: what the
   * timesheet views show (#89). */
  mirror: Mirror;
  projects: RawNamed[];
  members: RawNamed[];
}

/** Saving rows: `done` of `total` projected entries (#89 frame H). */
export interface SyncProgress {
  phase: 'save';
  done: number;
  total: number;
}

export interface LogReport {
  /** Incrementals stored by this sync; 0 when nothing changed. */
  incrementals: number;
  snapshotWritten: boolean;
  /** Entries missing from a complete list read, re-checked next sync. */
  candidates: number;
  /** Milliseconds of the look-back window no complete read covers. */
  unknownMs: number;
}

export interface SyncOptions {
  /** Wall clock for observation timestamps. Defaults to `Date.now`. */
  clock?: () => number;
  /** Observation ids. Defaults to a time-ordered random id. */
  newId?: () => string;
  /** Names this app instance in the log. Defaults to a random id. */
  device?: string;
  onProgress?: (progress: SyncProgress) => void;
}

const randomHex = (bytes: number) =>
  Array.from(crypto.getRandomValues(new Uint8Array(bytes)), b =>
    b.toString(16).padStart(2, '0'),
  ).join('');

export const newObservationId = (clock: () => number = Date.now) =>
  `${clock().toString(36).padStart(9, '0')}-${randomHex(8)}`;

/** Generated per page load: the frame has no storage to keep one in. */
const SESSION_DEVICE = `frame-${randomHex(6)}`;

export const GENERATED_TABLE_NOTE =
  'Generated by the Clockify timesheets app from what it last read in Clockify. Read-only: edits made here are overwritten on the next sync.';

export function rowValues(
  entry: ProjectedEntry,
  row: Record<RowKey, string>,
): Record<string, JSONValue> {
  const values: Record<string, JSONValue> = {
    [NAME]: entry.name,
    [row.entryId]: entry.entryId,
    [row.start]: entry.start,
    [row.end]: entry.end,
  };
  if (entry.billable !== undefined) values[row.billable] = entry.billable;
  if (entry.projectId) values[row.projectId] = entry.projectId;
  if (entry.projectName) values[row.projectName] = entry.projectName;
  if (entry.memberId) values[row.memberId] = entry.memberId;
  if (entry.memberName) values[row.memberName] = entry.memberName;

  return values;
}

/**
 * One pass of the read-only observation log (#123 M1):
 *
 * 1. Confirm the absence candidates of earlier passes with a GET by id each:
 *    404 confirms the deletion, 200 restores the entry (it was skipped or
 *    moved, not deleted). A failing GET leaves the candidate for next time.
 * 2. Read the look-back window, starting 24 h earlier (the margin), as one
 *    observation; append it as a mask-diff against the mirror. The bounds
 *    are sent as wall-clock time in the user's profile time zone, read
 *    from `GET /user` each pass along with the workspace's
 *    `forceProjects`, and recorded as the UTC span they cover.
 * 3. Compact when the tail is long enough, and save the log head.
 * 4. Project the mirror onto the table's rows. The rows are a read-only
 *    projection (#97 answer 2): completed `REGULAR` entries (the lens skips
 *    running timers and breaks) are created or updated by
 *    `clockify-entry-id`, and a row whose entry Clockify confirmed deleted
 *    is destroyed. Edits made in the table are overwritten.
 *
 * A failure of the window's first page fails the pass; only step 1's
 * re-checks, if any, are saved. A failure on a later page keeps what was
 * read (incomplete: no absences, no coverage), saves it, and fails the pass.
 * Either way the rows are not touched. Nothing is written to Clockify.
 *
 * Row identity is a stored `clockify-entry-id` found with `store.query()`,
 * restricted to children of the app's table (`query` is drive-scoped).
 * Requests are sequential; each is one `store.proxy.request` round trip.
 */
export async function syncClockify(
  store: PluginStore,
  transport: ProxyTransport,
  settings: Settings,
  schema: CompleteSchema,
  now = Date.now(),
  options: SyncOptions = {},
): Promise<SyncResult> {
  const clock = options.clock ?? Date.now;
  const account = await fetchAccountContext(transport, settings.workspaceId);
  const context: ReadContext = {
    transport,
    workspaceId: settings.workspaceId,
    userId: settings.userId,
    ...(account.timeZone ? { timeZone: account.timeZone } : {}),
    clock,
    newId: options.newId ?? (() => newObservationId(clock)),
    device: options.device ?? SESSION_DEVICE,
  };
  const log = await ObservationLog.open(store, schema, { clock });
  const warnings: string[] = [...account.warnings];

  for (const candidate of absenceCandidates(log.mirror)) {
    try {
      await log.append(await readOne(context, candidate.id));
    } catch (error) {
      warnings.push(
        `Could not re-check entry ${candidate.id}: ${error instanceof Error ? error.message : String(error)}`,
      );
    }
  }

  const window = { from: now - settings.lookbackDays * DAY, to: now };
  let read: Awaited<ReturnType<typeof readRange>>;

  try {
    read = await readRange(context, window.from - MARGIN_MS, window.to);
  } catch (error) {
    await log.flush();
    throw error;
  }

  await log.append(read.observation);

  if (read.error) {
    await log.flush();
    throw read.error;
  }

  const projects = await fetchNamed(
    transport,
    settings.workspaceId,
    'projects',
  );
  const members = await fetchNamed(transport, settings.workspaceId, 'users');
  warnings.push(
    ...[projects.warning, members.warning].filter((w): w is string => !!w),
  );
  const snapshotWritten = await log.compactIfNeeded();
  await log.flush();

  const rows = await projectRows(
    store,
    schema,
    log,
    projects.items,
    members.items,
    options.onProgress,
  );

  return {
    ...rows,
    warnings,
    log: {
      incrementals: log.appended,
      snapshotWritten,
      candidates: absenceCandidates(log.mirror).length,
      unknownMs: totalMs(unknownIntervals(log.mirror, settings, window, now)),
    },
    account: {
      ...(account.timeZone ? { timeZone: account.timeZone } : {}),
      ...(account.forceProjects !== undefined
        ? { forceProjects: account.forceProjects }
        : {}),
      ...(account.weekStart ? { weekStart: account.weekStart } : {}),
    },
    mirror: log.mirror,
    projects: projects.items,
    members: members.items,
  };
}

async function projectRows(
  store: PluginStore,
  schema: CompleteSchema,
  log: ObservationLog,
  projects: Parameters<typeof projectEntries>[1],
  members: Parameters<typeof projectEntries>[2],
  onProgress?: SyncOptions['onProgress'],
) {
  const result = { created: 0, updated: 0, unchanged: 0, removed: 0 };
  const own = new Set(
    await store.query({ property: atomic.parent, value: schema.table }),
  );
  const rowOf = async (entryId: string) =>
    (await store.query({ property: schema.row.entryId, value: entryId })).find(
      s => own.has(s),
    );

  const table = await store.getResource(schema.table);

  if (!table.get(atomic.description)) {
    table.set(atomic.description, GENERATED_TABLE_NOTE);
    await table.save();
  }

  const entries = timeEntries(log.mirror);
  const projected = projectEntries(
    entries.filter(r => !r.deletedAt).map(rawFromCanonical),
    projects,
    members,
  ).sort((a, b) => a.start - b.start || (a.entryId < b.entryId ? -1 : 1));

  for (const [done, entry] of projected.entries()) {
    onProgress?.({ phase: 'save', done, total: projected.length });
    const values = rowValues(entry, schema.row);
    const subject = await rowOf(entry.entryId);

    if (!subject) {
      const created = await store.newResource({
        parent: schema.table,
        isA: [schema.rowClass],
        propVals: values,
      });
      own.add(created.subject);
      result.created++;
      continue;
    }

    const existing = await store.getResource(subject);
    const changed = Object.entries(values).filter(
      ([property, value]) => existing.get(property) !== value,
    );

    if (!changed.length) {
      result.unchanged++;
      continue;
    }

    for (const [property, value] of changed) existing.set(property, value);
    await existing.save();
    result.updated++;
  }

  for (const gone of entries.filter(r => r.deletedAt)) {
    const subject = await rowOf(gone.id);
    if (!subject) continue;
    await (await store.getResource(subject)).destroy();
    own.delete(subject);
    result.removed++;
  }

  return result;
}
